language: python
branches:
  - jasy08
python:
  - 3.2
script:
  - ln -s `which python` python3; env PATH="$PATH:`pwd`" bin/jasy create --name mytest --origin https://github.com/zynga/core.git --skeleton application
